version: '3.3'

services: 
  mysql-db:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=p4$$w0rd
      - MYSQL_ROOT_PASSWORD=p4$$w0rd
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - internalnet
  
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeap:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB_HOST=68.70.164.5
      - DB_PORT=3306
      - DB_USER=mouchane_userdb_user
      - DB_PASSWORD=Suecia1357911
      - DB_NAME=mouchane_userdb
      - DB_CONNECTION_LIMIT=20
      - SERVICE_TAGS=prod
      - SERVICE_NAME=nodeappservice
      - SERVER_PORT=3000
    depends_on:
      - mysql-db
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge